### ISSUE TITLE
dyld: Library not loaded: @rpath/PushMenu.framework/PushMenu

### ISSUE THREAD

**Issue by jerkoch** [saoudrizwan/PushMenu#2]
The `PushMenuExample` target is missing the `PushMenu.framework` in the Embedded Binaries section.  Works fine on the simulator, but fails on a device.

**Comment by saoudrizwan** [comment]
Hmm, I linked the framework to the example project and everything worked fine in the original master workspace... but I just added another copy of the framework to the example project and added it to the embedded binaries, can you try it now and see if it works pls?

**Comment by saoudrizwan** [comment]
Alright I tested it and everything should work fine now.. thanks for the issue, this is my first time making a framework bundle like this.

**Comment by jerkoch** [comment]
Works like a charm! 👍
